// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function AddClazz(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function BatchAddClazz(arg1:string,arg2:string,arg3:Array<{[key: string]: string}>,arg4:number,arg5:string):Promise<void>;

export function CrazyBatchAddClazz(arg1:string,arg2:string,arg3:Array<{[key: string]: string}>,arg4:number):Promise<void>;

export function DelClazz(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function NormalBatchAddClazz(arg1:string,arg2:string,arg3:Array<{[key: string]: string}>,arg4:number):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function VerifyToken(arg1:string,arg2:string):Promise<string>;
