// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function AddClazz(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function VerifyToken(arg1:string,arg2:string):Promise<string>;
