// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Second(arg1:number,arg2:number):Promise<number>;

export function Startup(arg1:context.Context):Promise<void>;
