// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Second(arg1, arg2) {
  return window['go']['Second']['App']['Second'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['Second']['App']['Startup'](arg1);
}
