// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';
import {context} from '../models';

export function GetCaptcha():Promise<{[key: string]: string}>;

export function QueryAllGrade(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:{[key: string]: http.Cookie}):Promise<{[key: string]: any}>;

export function SaveGradeToFile(arg1:{[key: string]: any}):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
