// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';
import {context} from '../models';

export function LoginToJwgl(arg1:string,arg2:string,arg3:string):Promise<{[key: string]: http.Cookie}>;

export function Startup(arg1:context.Context):Promise<void>;
