// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function QueryAllGrade(arg1:string,arg2:string,arg3:string):Promise<{[key: string]: any}>;

export function SaveGradeToFile(arg1:{[key: string]: any}):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
