// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCaptcha() {
  return window['go']['login']['App']['GetCaptcha']();
}

export function QueryAllGrade(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['login']['App']['QueryAllGrade'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SaveGradeToFile(arg1) {
  return window['go']['login']['App']['SaveGradeToFile'](arg1);
}

export function Startup(arg1) {
  return window['go']['login']['App']['Startup'](arg1);
}
