// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetXGKC(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function Startup(arg1:context.Context):Promise<void>;
