// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Check_now_is_latest(arg1:string,arg2:string):Promise<boolean>;

export function Download_config_file():Promise<boolean>;

export function Get_config_file_path():Promise<string>;

export function Get_current_program_path():Promise<string>;

export function Get_latest_version_code():Promise<string>;

export function Get_version_code():Promise<string>;

export function Settings(arg1:number,arg2:number):Promise<number>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateAndRestart():Promise<void>;
